name: Automated NoSQL Data Ingestion Pipeline

on:
  schedule:
    # Se ejecuta automáticamente todos los lunes a las 08:00 UTC (Alineado con flujos de negocio)
    - cron: '0 8 * * 1'
  workflow_dispatch:
    # Permite la ejecución manual con un solo clic desde la interfaz de GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # Optimiza el tiempo de ejecución almacenando dependencias

    - name: Install Architecture Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Ingestion and Analytics Pipeline
      env:
        # Inyecta de forma segura el secreto guardado en el entorno virtual de ejecución
        MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      run: |
        python src/main.py
